MediaArea/homebrew-mediaarea

README.md, mediaconch-gui.rb, mediainfo-gui.rb
=> Add formulae for mediainfo-gui and mediaconch-gui

README.md
=> Revert to lowercase github account name in README.md

mediaconch-gui.rb
=> Fix mediaconch-gui

.travis.yml, mediaconch-gui.rb
=> add travis tests

avimetaedit.rb, bwfmetaedit.rb, dvanalyzer.rb
=> CLI formulae

movmetaedit-gui.rb, movmetaedit.rb
=> MOVMetaEdit formulae

movmetaedit.rb
=> shorter description

rawcooked.rb
=> RAWCooked formulae

rawcooked.rb
=> Update rawcooked snapshot to version 20180514

Casks/mediaconch-gui.rb
=> Add cask for mediaconch

.travis.yml, dvrescue.rb
=> Add formula for dvrescue

dvrescue.rb
=> Update dvrescue to version 0.20.05

dvrescue.rb
=> Update dvrescue to version 0.20.06

.github/workflows/homebrew-mediaarea_Checks.yml, .travis.yml
=> Switch from travis-ci to github-actions

dvrescue.rb
Fix https://github.com/mipops/dvrescue/pull/101#issuecomment-758904885.
=> Add xmlstarlet dependancy to dvrescue formula

bwfmetaedit-gui.rb
=> bwfmetaedit-gui v21.07

mediainfo-gui.rb
=> Fix typo in mediainfo-gui formula

.github/workflows/homebrew-mediaarea_Checks.yml, rawcooked.rb
=> RAWcooked v21.09

mediainfo-gui.rb
=> mediainfo-gui v21.09

mediainfo-gui.rb
=> mediainfo-gui v22.03

mediainfo-gui.rb
=> mediainfo-gui v22.06

mediainfo-gui.rb
=> mediainfo-gui -v22.09

dvrescue.rb
=> dvrescue v0.22.10

bwfmetaedit-gui.rb
=> bwfmetaedit-v22.11

mediainfo-gui.rb
=> mediainfo-gui v22.12

.github/workflows/homebrew-mediaarea_Checks.yml, Casks/dvrescue-gui.rb
=> Add cask formula for dvrescue-gui

ffmpeg-ma.rb
=> ffmpeg-ma: enable ffplay

ffmpeg-ma.rb
libiec61883 is not available through Homebrew. Therefore, the library and its development package should be installed on the target system using the native package manager.
=> ffmpeg-ma: Add --with-iec61883 option on Linux
